name: Eureka / SonarCloud Scanning WebGoat

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  eureka-scan:
    runs-on: ubuntu-latest
    name: scan
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Pull and Run Eureka
        run: |
          docker login -u ${{ secrets.EUREKA_USER }} -p ${{ secrets.EUREKA_PASSWORD }} ${{ vars.EUREKA_REGISTRY_URL }}
          #echo "${{ secrets.EUREKA_PASSWORD }}" | docker login --username ${{ secrets.EUREKA_USER }} --password-stdin ${{ vars.EUREKA_REGISTRY_URL }}
          echo "Using these for pull: ${{ vars.EUREKA_REGISTRY_URL }}/${{ vars.EUREKA_REPO }}:${{ vars.EUREKA_TAG }}"
          docker pull ${{ vars.EUREKA_REGISTRY_URL }}/${{ vars.EUREKA_REPO }}:${{ vars.EUREKA_TAG }}      
          echo "Using these for docker run:  ${{ vars.EUREKA_REGISTRY_URL }}/${{ vars.EUREKA_REPO }}:${{ vars.EUREKA_TAG }}"
          docker run --rm --network host \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)":/home/repo \
          -e DIND_USER_HOME="$(pwd)" \
          -e SONAR_USER_TOKEN=$SONAR_USER_TOKEN  \
          -e EUREKA_ENDPOINT="${{ secrets.EUREKA_ENDPOINT }}" \
          -e EUREKA_USER=${{ secrets.EUREKA_USER }} \
          -e EUREKA_PASSWORD=${{ secrets.EUREKA_PASSWORD }} \
          -e PROFILE_INFO=${{ vars.PROFILE_INFO_WEBGOAT_SONARCLOUD }} \
          ${{ vars.EUREKA_REGISTRY_URL }}/${{ vars.EUREKA_REPO }}:${{ vars.EUREKA_TAG }}
